name: Build Custom SaaS App

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'Uygulama Paket Adı'
        required: true
      app_name:
        description: 'Uygulama Görünür Adı'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # v3 yerine v4

      - name: Set up JDK 17 # Daha kararlı bir sürüm
        uses: actions/setup-java@v4 # v3 yerine v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Change Package Name & App Name
        run: |
          # Paket adını build.gradle içinde dinamik değiştir
          sed -i "s/com.kodhocasi.template/${{ github.event.inputs.package_name }}/g" app/build.gradle
          # Uygulama ismini strings.xml içinde değiştir
          sed -i "s/TemplateApp/${{ github.event.inputs.app_name }}/g" app/src/main/res/values/strings.xml

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4 # İŞTE BURASI! Hatayı çözen güncelleme
        with:
          name: ${{ github.event.inputs.app_name }}-Release-APK
          path: app/build/outputs/apk/release/*.apk
          retention-days: 5 # SaaS için ideal, 5 gün sonra silinir, yer kaplamaz
